---
# Reusable task file to install Terraform

- name: "Check if Terraform is installed"
  ansible.builtin.stat:
    path: ~/.local/bin/terraform
  register: terraform_check

- name: "Install Terraform"
  ansible.builtin.shell: |
    cd /tmp
    curl -sL https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip -o terraform.zip
    unzip -o terraform.zip
    chmod +x terraform
    mkdir -p ~/.local/bin
    mv terraform ~/.local/bin/terraform
    rm -f terraform.zip
  when: not terraform_check.stat.exists
  changed_when: true