---
terraform_dir: "{{ playbook_dir }}/../../terraform"

aws_region: "us-east-1"

vpc_cidr: "10.0.0.0/16"
public_subnet_cidr: "10.0.1.0/24"
availability_zone: "us-east-1a"

bucket_name: "partha-todo-app-2026"

instance_type: "t3.micro"

key_name: "todo-ec2-key"

resource_action: "all"
