---
- name: Deploy AWS infrastructure using Terraform
  hosts: terraform
  gather_facts: false

  vars:
    terraform_dir: "{{ playbook_dir }}/../../terraform"

    tools_dir: "/runner/project/.tools"

    terraform_binary: "/runner/project/.tools/terraform"

    aws_binary: "/runner/project/.tools/aws"

    terraform_version: "1.13.4"

  tasks:

    - name: Install AWS CLI
      ansible.builtin.include_tasks:
        file: "../tasks/install-awscli.yml"

    - name: Install Terraform
      ansible.builtin.include_tasks:
        file: "../tasks/install-terraform.yml"

    - name: Deploy Terraform infrastructure
      ansible.builtin.include_tasks:
        file: "../tasks/terraform.yml"