---
- name: Deploy AWS infrastructure using Terraform
  hosts: terraform
  gather_facts: false

  tasks:

    - name: Install AWS CLI
      ansible.builtin.include_tasks:
        file: "../tasks/install-awscli.yml"

    - name: Install Terraform
      ansible.builtin.include_tasks:
        file: "../tasks/install-terraform.yml"

    - name: Deploy Terraform infrastructure
      ansible.builtin.include_tasks:
        file: "../tasks/terraform.yml"